version: "3.8"
services:
  app:
    build: .
    volumes:
     - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
    command: python manage.py runserver 127.0.0.1:8000
    